ML-042/add elasticsearch
iTechArt-RubyLab/movie-land pull request #48
Opened 2022-03-02 03:26 UTC by WhatWasThatt

# Description

add elasticsearch gem
config elasticsearch
...

## Trello card link

https://trello.com/c/L6ii8tU6

# Checklist:

- [ ] My code fixes the problem or adds required functionality
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove that my feature works
- [ ] New and existing unit tests pass locally with my changes

# Additional requirements:

- [ ] Does your code require any migrations to be ran?
- [ ] Does your code require installing any new gems or system dependencies?
- [ ] Does your code require any changes to current deployment process?

# Additional Information

2022-03-03 23:18 UTC, KarinaKlevzhits submitted a review, later dismissed
for me looks good!

2022-03-05 00:52 UTC, dmitrymalllpr requested changes

2022-03-05 00:52 UTC, dmitrymalllpr commented on app/controllers/home_controller.rb
> +  def search
refactor please

2022-03-08 21:29 UTC, KarinaKlevzhits submitted a review, later dismissed

2022-03-11 21:24 UTC, dmitrymalllpr approved these changes

2022-03-11 23:11 UTC, KarinaKlevzhits approved these changes

2022-03-11 23:31 UTC, dmitrymalllpr approved these changes

2022-03-11 23:32 UTC, merged