ML-039/add carrierwave
iTechArt-RubyLab/movie-land pull request #49
Opened 2022-03-02 15:35 UTC by twill11

# Description

Add carrierwave and cloudinary
Store pictures to cdn and locally
Add upload from url

## Trello card link

https://trello.com/c/gpML94eX/37-ml-039-add-carrierwave

# Checklist:

- [ ] My code fixes the problem or adds required functionality
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove that my feature works
- [ ] New and existing unit tests pass locally with my changes

# Additional requirements:

- [ ] Does your code require any migrations to be ran?
- [ ] Does your code require installing any new gems or system dependencies?
- [ ] Does your code require any changes to current deployment process?

# Additional Information

2022-03-05 00:50 UTC, dmitrymalllpr requested changes

2022-03-05 00:50 UTC, dmitrymalllpr commented on config/initializers/carrierwave.rb
> +end
add line

2022-03-05 18:59 UTC, WhatWasThatt reviewed
can you update the tests with the new changes?

2022-03-05 18:59 UTC, WhatWasThatt commented on app/uploaders/poster_uploader.rb
> +class PosterUploader < CarrierWave::Uploader::Base
repeated code

2022-03-08 23:20 UTC, WhatWasThatt approved these changes

2022-03-08 23:55 UTC, dmitrymalllpr requested changes

2022-03-08 23:55 UTC, dmitrymalllpr commented on app/controllers/api/v1/movies_controller.rb
> +        if @movie.update!(movie_params)
Why did you use bang ?

2022-03-09 00:53 UTC, dmitrymalllpr approved these changes

2022-03-09 01:10 UTC, KarinaKlevzhits approved these changes

2022-03-09 01:33 UTC, merged