ML-040/add sidekiq
iTechArt-RubyLab/movie-land pull request #52
Opened 2022-03-04 02:22 UTC by KarinaKlevzhits

# Description

Please include a brief summary of changes introduces. For bug fixes describe which issue is fixed. Please also include relevant motivation and context.

## Trello card link

Insert a Trello card link instead of this line. If corresponding Trello task does not exists, create it first.

# Checklist:

- [ ] My code fixes the problem or adds required functionality
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove that my feature works
- [ ] New and existing unit tests pass locally with my changes

# Additional requirements:

- [ ] Does your code require any migrations to be ran?
- [ ] Does your code require installing any new gems or system dependencies?
- [ ] Does your code require any changes to current deployment process?

# Additional Information

2022-03-04 02:34 UTC, WhatWasThatt submitted a review, later dismissed
Really good job!

2022-03-04 03:03 UTC, dmitrymalllpr requested changes

2022-03-04 03:03 UTC, dmitrymalllpr commented on app/service/reviewer_notification_service.rb
> +    end
call_mailer(movies,user)

2022-03-04 03:03 UTC, dmitrymalllpr commented on app/mailers/redactor_mailer.rb
> +end
remove repeated code please

2022-03-04 06:07 UTC, twill11 commented on app/service/redactor_notification_service.rb
> +    RedactorMailer.redactor_notification(ratings, redactor).deliver_now
dont use deliver or deliver_now please improve, https://medium.com/@coorasse/the-correct-emails-configuration-in-rails-c1d8418c0bfd

2022-03-04 14:38 UTC, ShrewHools commented on app/views/redactor_mailer/redactor_notification.html.erb
> +   <% @ratings.each do |rating| %>
maybe move each above tag 'p'?

2022-03-04 14:38 UTC, ShrewHools commented on app/views/redactor_mailer/redactor_notification.html.erb
> +    Rating: <%= rating[:rating] %> Movie: <%= rating[:"movies.name"]%> User: <%= rating[:"users.name"] %> </br>
hash[:'String']
why?

2022-03-04 14:38 UTC, ShrewHools commented on app/service/reviewer_notification_service.rb
> +class ReviewerNotificationService
what is the meaning of class_service.rb file name in services folder?
i mean **_service**

2022-03-04 14:38 UTC, ShrewHools commented on app/service/redactor_notification_service.rb
> +    ratings = Rating.where(created_at: Date.yesterday).joins(:movie, :user).pluck('rating', 'movies.name', 'users.name')
can we use **select** and remove **.map {}**?

2022-03-04 14:38 UTC, ShrewHools commented on app/service/redactor_notification_service.rb
> +class RedactorNotificationService
maybe you can put all the notifications in a folder? to make it easier for other users to use the services folder?

2022-03-04 14:38 UTC, ShrewHools commented on config/environments/development.rb
> +  config.active_job.queue_adapter = :sidekiq
do you really need this line?
will something break if you remove it?

2022-03-06 21:23 UTC, WhatWasThatt approved these changes

2022-03-08 20:45 UTC, merged